version: '3'
services:
  otel-python:
    build: .
    volumes:
      - ./data:/app/data
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector:4317
      - OTEL_EXPORTER_OTLP_HTTP_ENDPOINT=http://collector:4318
      - OTEL_SERVICE_NAME=otel-python-example
      - OTEL_RESOURCE_ATTRIBUTES="service.version=1.0,deployment.environment=dev"
    depends_on:
      - collector

  collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./collector/collector.yml:/collector.yml
    command: ["--config=/collector.yml"]
    env_file:
        - .env
    ports:
      - "4317:4317"
      - "4318:4318"